// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import "@vue/runtime-core";

export {};

declare module "@vue/runtime-core" {
    export interface GlobalComponents {
        ElInputNumber: typeof import("element-plus/es")["ElInputNumber"];
        ElOption: typeof import("element-plus/es")["ElOption"];
        ElProgress: typeof import("element-plus/es")["ElProgress"];
        ElRadio: typeof import("element-plus/es")["ElRadio"];
        ElRadioGroup: typeof import("element-plus/es")["ElRadioGroup"];
        ElSelect: typeof import("element-plus/es")["ElSelect"];
        ElSwitch: typeof import("element-plus/es")["ElSwitch"];
    }
}
