// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module "vue" {
    export interface GlobalComponents {
        ElInputNumber: typeof import("element-plus/es")["ElInputNumber"];
        ElProgress: typeof import("element-plus/es")["ElProgress"];
        ElRadio: typeof import("element-plus/es")["ElRadio"];
        ElRadioGroup: typeof import("element-plus/es")["ElRadioGroup"];
    }
}

export {};
