export const defaultnumberofants = 10;
export const defaultsearchrounds = 10;
export const default_local_pheromone_volatilization_rate = 0.035;
export const default_global_pheromone_volatilization_rate = 0.3;
// export const default_searchloopcountratio = 15;
export const default_alpha = 1;
export const default_beta = 5;
export const default_pheromoneintensityQ = 1;
export const default_max_results_of_k_opt = 20;
